#!/bin/sh

#We check here that the text has the following syntax:
#starts with two or three letters (initials) , a dash, 
#then between one and seven digits, and finally a dash

validentry=$(head -1 $1|grep -c -P '^[A-Z]{2,3}-#\d{1,7}-')
if [ $validentry -ne 0 ]
  then
    exit 0
  else
    echo '[POLICY] Your commit message is not formatted properly'
    echo '[POLICY] The first line must start with your initials (2 or 3 chars)'
    echo '[POLICY] followed by a dash, a hash, and up to 7 digits'
    echo '[POLICY] and then a final dash, and then just enter your message,'
    echo '[POLICY] like this: '
    echo '[POLICY]     BK-#123- Whatever'
    echo '[POLICY]'
    echo '[POLICY] commit hook configured in commit-msg in git config dir'
    exit 1
  fi
