truncate localization_lookup;

---DELIMITER---

-- insert into the lookup table for words and 
-- phrases to their localized counterparts, e.g. French, English, etc.
INSERT INTO localization_lookup(local_id, language, text)
VALUES
  (1,   1,  'Search'),
  (2,   1,  'Request Favor'),
  (3,   1,  'Logout'),
  (4,   1,  'Points'),
  (5,   1,  'Please enter a description'),
  (6,   1,  'Publish'),
  (7,   1,  'Current location'),
  (8,   1,  'Your groups'),
  (9,   1,  'is owed %d favors'),
  (10,  1,  'Description'),
  (11,  1,  'Rank average'),
  (12,  1,  'Rank score'),
  (13,  1,  'Categories'),
  (14,  1,  'Request Favor with location'),
  (15,  1,  'Location details'),
  (16,  1,  'The dashboard'),
  (17,  1,  'to'),
  (18,  1,  'Rank average'),
  (19,  1,  'Rank ladder'),
  (20,  1,  'Copy the following text and send it to whoever you are inviting to the system'),
  (21,  1,  'Delete'),
  (22,  1,  'Favor Details'),
  (23,  1,  'Hi! Join me and my friends on a system that encourages trading of favors, at'),
  (24,  1,  'Status'),
  (25,  1,  'Date'),
  (26,  1,  'You are a member of these groups'),
  (27,  1,  'owes people %d favors'),
  (28,  1,  'Categories'),
  (29,  1,  'Yes, delete!'),
  (30,  1,  'Nevermind, do not delete it'),
  (31,  1,  'Favor has been deleted'),
  (32,  1,  'Favor'),
  (33,  1,  'deleted'),
  (34,  1,  'This favor has been deleted, its points have been refunded to you'),
  (35,  1,  'Dashboard'),
  (36,  1,  'Send message'),
  (37,  1,  'Handle'),
  (38,  1,  'Message(up to %d characters)'),
  (39,  1,  'Are you sure you want to delete this favor?'),
  (40,  1,  'You own these groups'),
  (41,  1,  'Error deleting favor'),
  (42,  1,  'Login'),
  (43,  1,  'Register'),
  (44,  1,  'Welcome to Zenia!'),
  (45,  1,  'Create a group'),
  (46,  1,  'General Error'),
  (47,  1,  'Please enter a password'),
  (48,  1,  'Please enter a username'),
  (49,  1,  'Invalid username / password combination'),
  (50,  1,  'Login page'),
  (51,  1,  'Username'),
  (52,  1,  'Password'),
  (53,  1,  'Group name'),
  (54,  1,  'A name is required for this group'),
  (55,  1,  'Create my new group'),
  (56,  1,  'Details of the group'),
  (57,  1,  'That user already exists'),
  (58,  1,  'Account Creation'),
  (59,  1,  'Owner'),
  (60,  1,  'Members'),
  (61,  1,  'Send invite'),
  (62,  1,  'Edit my group description'),
  (63,  1,  'Password'),
  (64,  1,  'Create my new user!'),
  (65,  1,  'Logged out'),
  (66,  1,  'You have successfully logged out'),
  (67,  1,  'Security problem'),
  (68,  1,  'You need to be logged in to access this.'),
  (69,  1,  'Thanks for registering!'),
  (70,  1,  'You are awesome! Thanks so much for entering your name!'),
  (71,  1,  'Your description as seen by others in your group'),
  (72,  1,  'Save description'),
  (73,  1,  'Your current location is'),
  (74,  1,  'Select country'),
  (75,  1,  'Done entering postal code'),
  (76,  1,  'Open'),
  (77,  1,  'Closed'),
  (78,  1,  'Taken'),
  (79,  1,  'Rank'),
  (80,  1,  'User'),
  (81,  1,  'Advanced search'),
  (82,  1,  'No locations found in database for this country and postcode'),
  (83,  1,  'Invalid date - try something like 2014-1-2 for January 2, 2014'),
  (84,  1,  'Edit description'),
  (85,  1,  'No users found in string'),
  (86,  1,  'Start date'),
  (87,  1,  'End date'),
  (88,  1,  'Remove this user'),
  (89,  1,  'Confirm password'),
  (90,  1,  'Your group''s description'),
  (91,  1,  'Set email address'),
  (92,  1,  'Email address'),
  (93,  1,  'Page'),
  (94,  1,  'Handle favor'),
  (95,  1,  'Confirm'),
  (96,  1,  'My conversations'),
  (97,  1,  'My profile'),
  (98,  1,  'Transaction is complete'),
  (99,  1,  'Favor has been closed'),
  (100, 1,  'Owning user'),
  (101, 1,  'Handling user'),
  (102, 1,  'Favors I am handling'),
  (103, 1,  'None'),
  (104, 1,  'Offer received'),
  (105, 1,  'We got your offer and will show it to that user shortly.'),
  (106, 1,  'new'),
  (107, 1,  'accepted'),
  (108, 1,  'rejected'),
  (109, 1,  'Draft'),
  (110, 1,  'Favor published'),
  (111, 1,  'Other users can now view your favor and may offer to handle it.'),
  (112, 1,  'Password changed'),
  (113, 1,  'Change password'),
  (114, 1,  'You entered no old password or new password.  Try again.'),
  (115, 1,  'You provided a new password, but you need to give us your old password too.'),
  (116, 1,  'You forgot to give us your new password.  Try again.'),
  (117, 1,  'Your new password is too short.  Try again.'),
  (118, 1,  'What you gave for your old password is not valid. Try again.'),
  (119, 1,  'Favors I have offered to service'),
  (120, 1,  'Offers to service my favors'),
  (121, 1,  'If you would like to offer to service this favor, click the confirm button below.'),
  (122, 1,  'My open Favors'),
  (123, 1,  'My Favors being serviced'),
  (124, 1,  'My closed Favors'),
  (125, 1,  'My draft Favors'),
  (126, 1,  'Cancel an active Favor'),
  (127, 1,  'Favor canceled'),
  (128, 1,  'Your transaction has been canceled'),
  (129, 1,  'If you would like to cancel this active Favor, click the confirm button below.  This will give you the chance provide a grade for the other person, as well as giving them a chance to grade you.'),
  (130, 1,  'Cancel'),
  (131, 1,  'Your transaction on a favor has been canceled by the other party.'),
  (132, 1,  'Congratulations! You have been awarded the right to service a Favor.'),
  (133, 1,  'to grade user'),
  (134, 1,  'A Favor which you were handling has been completed.'),
  (135, 1,  'A Favor which you were owner of has been completed.'),
  (136, 1,  'You have canceled an active transaction.'),
  (137, 1,  'Choose'),
  (138, 1,  'wants to handle'),
  (139, 1,  'Choose a handler'),
  (140, 1,  'Confirm that you would like the following user to handle this request.'),
  (141, 1,  'You have selected a handler for your Favor!'),
  (142, 1,  'You have now selected someone to handle your favor.  That user will be informed, and we will also inform the other users (if any) that they have not been selected.'),
  (143, 1,  'Babysitting'),
  (144, 1,  'Dog-walking'),
  (145, 1,  'Taxi'),
  (146, 1,  'My system messages'),
  (147, 1,  'You should rank that user now.'),
  (148, 1,  'You have recieved an offer to handle a Favor.'),
  (149, 1,  'EMPTY'),
  (150, 1,  'EMPTY'),
  (151, 1,  'EMPTY'),
  (152, 1,  'Street Address 1'),
  (153, 1,  'Street Address 2'),
  (154, 1,  'City'),
  (155, 1,  'State'),
  (156, 1,  'Postal code'),
  (157, 1,  'Country'),
  (158, 1,  'Select one of your saved locations'),
  (159, 1,  'Or enter a new address'),
  (160, 1,  'Save to my favorites'),
  (161, 1,  'EMPTY'),
  (162, 1,  'EMPTY'),
  (163, 1,  'EMPTY'),
  (164, 1,  'EMPTY'),
  (165, 1,  'You'),
  (166, 1,  'EMPTY'),
  (167, 1,  'EMPTY'),
  (168, 1,  'EMPTY'),
  (169, 1,  'EMPTY'),
  (170, 1,  'EMPTY'),
  (171, 1,  'Message'),
  (172, 1,  'EMPTY'),
  (173, 1,  'Their open favors'),
  (174, 1,  'Old password'),
  (175, 1,  'New password'),
  (176, 1,  'EMPTY'),
  (177, 1,  'EMPTY'),
  (178, 1,  'EMPTY'),
  (179, 1,  'EMPTY'),
  (180, 1,  'EMPTY'),
  (181, 1,  'EMPTY'),
  (182, 1,  'EMPTY'),
  (183, 1,  'Favor created'),
  (184, 1,  'You have created a favor.  Right now, it is in draft mode, unviewable by other users. You may'),
  (185, 1,  'it now if you wish.  Until you publish, it will remain hidden.'),
  (186, 1,  'Rank user'),
  (187, 1,  'for the following Favor'),
  (188, 1,  'happy'),
  (189, 1,  'unhappy'),
  (190, 1,  'Ranking confirmed'),
  (191, 1,  'Thanks!  By providing a ranking for this user, you make the system a safer place for everyone.'),
  (192, 1,  'no address selected'),
  (193, 1,  'EMPTY'),
  (194, 1,  'Retract'),
  (195, 1,  'Favor retracted'),
  (196, 1,  'Your favor is now hidden.  Any offers have been rejected. A point has been returned to you.'),
  (197, 1,  'You must choose a category for this favor'),
  (198, 1,  'Select a category'),
  (199, 1,  'Miscellany'),
  (200, 1,  'Homework'),
  (201, 1,  'Invalid invite code'),
  (202, 1,  'Check invite code'),
  (203, 1,  'Invitation code'),
  (204, 1,  'Submit invite code'),
  (205, 1,  'An invitation code is required for registration'),
  (206, 1,  'Generate invitation code'),
  (207, 1,  'Here is an invitation code.  It is valid for a week'),
  (208, 1,  'Description text too large - please stay within 200 characters'),
  (209, 1,  'Change current location'),
  (210, 1,  'You have not provided any information on a current location.  There is a cancel button if you do not wish to add or change this'),
  (211, 1,  'At the very least, you must provide a postal code.  That''s what we use to determine your distance to favors'),
  (212, 1,  'Maximum distance in miles'),
  (213, 1,  'Distance error - needs to be a number'),
  (214, 1,  '%d seconds later'),
  (215, 1,  '%d minutes later'),
  (216, 1,  '%d hours later'),
  (217, 1,  '%d days later'),
  (218, 1,  '%d years later'),
  (219, 1,  'EMPTY'),
  (220, 1,  'EMPTY'),
  (221, 1,  'EMPTY'),
  (222, 1,  'You have joined a new group.  It is now listed in your groups page'),
  (223, 1,  'You have been removed from a group'),
  (224, 1,  'EMPTY'),
  (225, 1,  '%d seconds ago'),
  (226, 1,  '%d minutes ago'),
  (227, 1,  '%d hours ago'),
  (228, 1,  '%d days ago'),
  (229, 1,  '%d years ago'),
  (1,   2,  'Recherche'),
  (2,   2,  'Demande Favor'),
  (3,   2,  'Déconnexion'),
  (4,   2,  'Points'),
  (5,   2,  'Se il vous plaît entrer une description'),
  (6,   2,  'Publier'),
  (7,   2,  'Localisation actuelle'),
  (8,   2,  'Vos groupes'),
  (9,   2,  'est dû %d faveurs'),
  (10,  2,  'Description'),
  (11,  2,  'Moyenne de rang'),
  (12,  2,  'Résultat de classement'),
  (13,  2,  'Catégories'),
  (14,  2,  'Demande Faveur avec l''emplacement'),
  (15,  2,  'Situation détaillée'),
  (16,  2,  'Le tableau de bord'),
  (17,  2,  'de se'),
  (18,  2,  'Moyenne rang'),
  (19,  2,  'Rang échelle'),
  (20,  2,  'Copiez le texte suivant et l''envoyer à qui vous invitez au système'),
  (21,  2,  'Effacer'),
  (22,  2,  'Favoriser Détails'),
  (23,  2,  'Salut ! Joignez-vous à moi et mes amis sur un système qui encourage les échanges de faveurs , au'),
  (24,  2,  'Statut'),
  (25,  2,  'Date'),
  (26,  2,  'Vous êtes un membre de ces groupes'),
  (27,  2,  'le doit de personnes %d faveurs'),
  (28,  2,  'Catégories'),
  (29,  2,  'Oui, supprimer!'),
  (30,  2,  'Passons, ne pas le supprimer'),
  (31,  2,  'Faveur a été supprimé'),
  (32,  2,  'Favoriser'),
  (33,  2,  'supprimé'),
  (34,  2,  'Cette faveur a été supprimé, ses points ont été remboursés de vous'),
  (35,  2,  'Tableau de bord'),
  (36,  2,  'Envoyer un message'),
  (37,  2,  'Manipuler'),
  (38,  2,  'Message (jusqu''à %d caractères)'),
  (39,  2,  'Êtes-vous sûr de vouloir supprimer cette faveur?'),
  (40,  2,  'Vous êtes le propriétaire de ces groupes'),
  (41,  2,  'Erreur suppression faveur'),
  (42,  2,  'S''identifier'),
  (43,  2,  'Se enregistrer'),
  (44,  2,  'Bienvenue à Zenia!'),
  (45,  2,  'Créer un groupe'),
  (46,  2,  'Erreur générale'),
  (47,  2,  'Se il vous plaît entrer un mot de passe'),
  (48,  2,  'Se il vous plaît entrer un nom d''utilisateur'),
  (49,  2,  'Nom d''utilisateur valide / combinaison de mot de passe'),
  (50,  2,  'Page de connexion'),
  (51,  2,  'Nom d''utilisateur'),
  (52,  2,  'Mot de passe'),
  (53,  2,  'Nom du groupe'),
  (54,  2,  'Un nom est nécessaire pour ce groupe'),
  (55,  2,  'Créer mon nouveau groupe'),
  (56,  2,  'Détails du groupe'),
  (57,  2,  'Cet utilisateur existe déjà'),
  (58,  2,  'Création d''un compte'),
  (59,  2,  'Propriétaire'),
  (60,  2,  'Membres'),
  (61,  2,  'Envoyer inviter'),
  (62,  2,  'Modifier la description de mon groupe'),
  (63,  2,  'Mot de passe'),
  (64,  2,  'Créer mon nouvel utilisateur!'),
  (65,  2,  'Déconnecté'),
  (66,  2,  'Vous avez enregistré avec succès'),
  (67,  2,  'Problème de sécurité'),
  (68,  2,  'Vous devez être connecté pour accéder à cette'),
  (69,  2,  'Merci de vous inscrire!'),
  (70,  2,  'Vous êtes génial! merci beaucoup pour saisir votre nom!'),
  (71,  2,  'Votre description comme on le voit par d''autres dans votre groupe'),
  (72,  2,  'Enregistrer la description'),
  (73,  2,  'Votre position actuelle est'),
  (74,  2,  'Choisissez un pays'),
  (75,  2,  'Fait entrer un code postal'),
  (76,  2,  'ouvert'),
  (77,  2,  'fermé'),
  (78,  2,  'pris'),
  (79,  2,  'Rang'),
  (80,  2,  'Utilisateur'),
  (81,  2,  'Recherche avancée'),
  (82,  2,  'Pas de lieux trouvés dans la base pour ce pays et le code postal'),
  (83,  2,  'Date non valide'),
  (84,  2,  'Modifier la description'),
  (85,  2,  'Aucun membre trouvé dans la chaîne'),
  (86,  2,  'Date de début'),
  (87,  2,  'Date de fin'),
  (88,  2,  'Retirer cet utilisateur'),
  (89,  2,  'Confirmez le mot de passe'),
  (90,  2,  'La description de votre groupe'),
  (91,  2,  'Entrez l''adresse email'),
  (92,  2,  'Adresse e-mail'),
  (93,  2,  'Page'),
  (94,  2,  'Poignée faveur'),
  (95,  2,  'Confirmer'),
  (96,  2,  'Mes conversations'),
  (97,  2,  'Mon profil'),
  (98,  2,  'Transaction est terminée'),
  (99,  2,  'Faveur a été fermé'),
  (100, 2,  'Utilisateur propriétaire'),
  (101, 2,  'Manipulation utilisateur'),
  (102, 2,  'Faveurs que je me occupe'),
  (103, 2,  'Aucun'),
  (104, 2,  'Offre reçue'),
  (105, 2,  'Nous avons obtenu votre offre et nous allons montrer à l''utilisateur sous peu. Vous pouvez suivre cela sur votre page de profil.'),
  (106, 2,  'nouveau'),
  (107, 2,  'accepté'),
  (108, 2,  'rejeté'),
  (109, 2,  'ébauche'),
  (110, 2,  'Favoriser publié'),
  (111, 2,  'Les autres utilisateurs peuvent désormais visualiser votre faveur et peuvent offrir à manipuler.'),
  (112, 2,  'Mot de passe modifié'),
  (113, 2,  'Changer le mot de passe'),
  (114, 2,  'Vous avez saisi ne ancien mot de passe ou un nouveau mot de passe. Essayer à nouveau.'),
  (115, 2,  'Vous avez fourni un nouveau mot de passe, mais vous devez nous donner votre ancien mot de passe trop.'),
  (116, 2,  'Vous avez oublié de nous donner votre nouveau mot de passe. Essayer à nouveau.'),
  (117, 2,  'Votre nouveau mot de passe est trop court. Essayer à nouveau.'),
  (118, 2,  'Qu''est-ce que vous avez donné à votre ancien mot de passe ne est pas valide. Essayer à nouveau.'),
  (119, 2,  'Faveurs que je ai offerts au service'),
  (120, 2,  'Offres de réparer mes faveurs'),
  (121, 2,  'Si vous souhaitez offrir au service de cette faveur, cliquez sur le bouton de confirmation ci-dessous.'),
  (122, 2,  'Mes Faveurs ouvertes'),
  (123, 2,  'Mes Faveurs étant desservis'),
  (124, 2,  'Mes Faveurs fermées'),
  (125, 2,  'Mes projets Favors'),
  (126, 2,  'Annuler une Favor actif'),
  (127, 2,  'Favoriser annulée'),
  (128, 2,  'Votre transaction a été annulée'),
  (129, 2,  'Si vous souhaitez annuler cette faveur actif, cliquez sur le bouton de confirmation ci-dessous. Cela vous donnera la chance de fournir une note pour l''autre personne, ainsi que de leur donner une chance de vous grade.'),
  (130, 2,  'Annuler'),
  (131, 2,  'Votre transaction sur une faveur a été annulé par l''autre partie. Découvrez votre page de profil pour entrer les informations sur cette transaction.'),
  (132, 2,  'Félicitations! Vous avez reçu le droit de desservir une faveur. Vérifiez votre profil pour plus d''informations.'),
  (133, 2,  'à l''utilisateur de qualité'),
  (134, 2,  'Une faveur qui vous manipulez a été achevée.'),
  (135, 2,  'Une faveur dont vous étiez propriétaire du a été achevée.'),
  (136, 2,  'Vous avez annulé une transaction active.'),
  (137, 2,  'Choisir'),
  (138, 2,  'veut gérer'),
  (139, 2,  'Choisissez un gestionnaire'),
  (140, 2,  'Confirmez que vous souhaitez l''utilisateur suivant pour gérer cette demande.'),
  (141, 2,  'Vous avez sélectionné un gestionnaire pour votre faveur!'),
  (142, 2,  'Vous avez maintenant sélectionné quelqu''un pour gérer votre faveur. Cet utilisateur sera informé, et nous informera également les autres utilisateurs (le cas échéant) qu''ils ne ont pas été sélectionnés.'),
  (143, 2,  'Garde d''enfants'),
  (144, 2,  'Promener son chien'),
  (145, 2,  'Taxi'),
  (146, 2,  'Mes messages système'),
  (147, 2,  'Vous devez classer cet utilisateur maintenant.'),
  (148, 2,  'Vous ai reçu une offre pour gérer une faveur.'),
  (149, 2,  'Est-ce que cette faveur besoin d''un emplacement?'),
  (150, 2,  'Oui'),
  (151, 2,  'Aucun'),
  (152, 2,  'Adresse 1'),
  (153, 2,  'Adresse 2'),
  (154, 2,  'Ville'),
  (155, 2,  'État'),
  (156, 2,  'Code Postal'),
  (157, 2,  'Pays'),
  (158, 2,  'Sélectionnez l''une de vos adresses enregistrées'),
  (159, 2,  'Ou entrer une nouvelle adresse'),
  (160, 2,  'Enregistrer à mes favoris'),
  (161, 2,  'Entrez une valeur de classement entre 0.0 et 1.0'),
  (162, 2,  'Entrez un code postal pour rechercher'),
  (163, 2,  'Invalide - doit être un nombre entre 0 et 1'),
  (164, 2,  'Invalide - maximale rang doit être supérieur rang minimum'),
  (165, 2,  'Vous'),
  (166, 2,  'augmenté'),
  (167, 2,  'diminué'),
  (168, 2,  'la réputation de'),
  (169, 2,  'votre réputation'),
  (170, 2,  'la faveur'),
  (171, 2,  'Message'),
  (172, 2,  'Timestamp'),
  (173, 2,  'Leurs faveurs ouvertes'),
  (174, 2,  'Ancien mot de passe'),
  (175, 2,  'Nouveau mot de passe'),
  (176, 2,  'Faveur Résolution'),
  (177, 2,  'Vous devez fournir une rétroaction sur'),
  (178, 2,  'Tu dors? Réveillez-vous! Vous avez'),
  (179, 2,  'secondes avant sont automatiquement déconnectés!'),
  (180, 2,  'n''a pas encore déterminé'),
  (181, 2,  'ne ont pas encore déterminé'),
  (182, 2,  'Je ne suis pas fait!'),
  (183, 2,  'Favoriser créé'),
  (184, 2,  'Vous avez créé une faveur. À l''heure actuelle, il est en mode brouillon, unviewable par d''autres utilisateurs. Vous pouvez'),
  (185, 2,  'maintenant si vous le souhaitez. Jusqu''à ce que vous publiez, il restera caché. Vous pouvez également publier cette faveur à partir de votre page de profil.'),
  (186, 2,  'utilisateur Rang'),
  (187, 2,  'Classer l''autre utilisateur pour la faveur suivante'),
  (188, 2,  'heureux'),
  (189, 2,  'malheureux'),
  (190, 2,  'Classement confirmé'),
  (191, 2,  'Merci! En fournissant un classement pour cet utilisateur, vous faites du système un endroit plus sûr pour tout le monde.'),
  (192, 2,  'aucune adresse sélectionnée'),
  (193, 2,  'Vous avez dit que vous vouliez enregistrer un emplacement avec cette faveur , mais vous avez entré rien. Si cela ne nécessite pas un emplacement , cliquez sur'),
  (194, 2,  'Rétracter'),
  (195, 2,  'Favoriser rétractée'),
  (196, 2,  'Votre faveur est maintenant caché . Les offres ont été rejetées . Un point a été retourné.'),
  (197, 2,  'Vous devez choisir une catégorie pour cette faveur'),
  (198, 2,  'Sélectionnez une catégorie'),
  (199, 2,  'Recueil'),
  (200, 2,  'Devoirs'),
  (201, 2,  'Invalid inviter le code'),
  (202, 2,  'Vérifiez inviter le code'),
  (203, 2,  'Code d''invitation'),
  (204, 2,  'Soumettre du code d''invitation'),
  (205, 2,  'Un code d''invitation est nécessaire pour l''inscription'),
  (206, 2,  'Générer du code d''invitation'),
  (207, 2,  'Voici un code d''invitation . Il est valable pour 30 minutes de cette époque'),
  (208, 2,  'Description Texte trop grande - se il vous plaît rester à moins de 200 caractères'),
  (209, 2,  'Changer l''emplacement actuel'),
  (210, 2,  'Vous ne avez pas fourni d''informations sur l''emplacement actuel . Il ya un bouton Annuler si vous ne souhaitez pas ajouter ou modifier ce'),
  (211, 2,  'À tout le moins , vous devez fournir un code postal . Ce est ce que nous utilisons pour déterminer votre distance faveurs'),
  (212, 2,  'Distance maximale en miles'),
  (213, 2,  'erreur de distance'),
  (214, 2,  '%d secondes plus tard'),
  (215, 2,  '%d minutes plus tard'),
  (216, 2,  '%d heures plus tard'),
  (217, 2,  '%d jours plus tard'),
  (218, 2,  '%d ans plus tard'),
  (219, 2,  'Votre invitation au groupe suivant a été retiré'),
  (220, 2,  'Vous avez rétractée votre invitation à l''utilisateur suivant'),
  (221, 2,  'L''utilisateur suivant a accepté votre invitation de groupe'),
  (222, 2,  'Vous avez rejoint un nouveau groupe . Elle est maintenant inscrite dans votre page des groupes'),
  (223, 2,  'Vous avez été supprimé d''un groupe'),
  (224, 2,  'Vous avez supprimé un utilisateur de votre groupe'),
  (225, 2,  '%d il ya secondes'),
  (226, 2,  '%d il y a quelques minutes'),
  (227, 2,  '%d il y a des heures'),
  (228, 2,  '%d il y a quelques jours'),
  (229, 2,  '%d il y a des années'),
  (1,   3,  'Búsqueda'),
  (2,   3,  'Solicitud Favor'),
  (3,   3,  'Cerrar sesión'),
  (4,   3,  'Puntos'),
  (5,   3,  'Por favor, introduzca una descripción'),
  (6,   3,  'Publicar'),
  (7,   3,  'Ubicación actual'),
  (8,   3,  'Sus grupos'),
  (9,   3,  'se le debe favores %d'),
  (10,  3,  'Descripción'),
  (11,  3,  'Rango promedio'),
  (12,  3,  'Puntuación de rango'),
  (13,  3,  'Categorías'),
  (14,  3,  'Solicitud Favor con la ubicación'),
  (15,  3,  'Ubicación detalles'),
  (16,  3,  'El tablero de instrumentos'),
  (17,  3,  'a la'),
  (18,  3,  'Rango promedio'),
  (19,  3,  'Escalera rango'),
  (20,  3,  'Copie el texto siguiente y enviarlo a cualquiera que te está invitando al sistema'),
  (21,  3,  'Borrar'),
  (22,  3,  'Favorecer Detalles'),
  (23,  3,  'Hola! Únete a mí y mis amigos en un sistema que fomenta el comercio de favores , en'),
  (24,  3,  'Estado'),
  (25,  3,  'Fecha'),
  (26,  3,  'Usted es un miembro de estos grupos'),
  (27,  3,  'le debe la gente %d favores'),
  (28,  3,  'Categorías'),
  (29,  3,  'Sí, borrar!'),
  (30,  3,  'No importa, no lo elimine'),
  (31,  3,  'Favor ha sido borrado'),
  (32,  3,  'Favorecer'),
  (33,  3,  'eliminado'),
  (34,  3,  'Este favor se ha eliminado, sus puntos se han devuelto a usted'),
  (35,  3,  'Salpicadero'),
  (36,  3,  'Enviar mensaje'),
  (37,  3,  'Manejar'),
  (38,  3,  'Mensaje (hasta %d caracteres)'),
  (39,  3,  '¿Seguro que quieres borrar este favor?'),
  (40,  3,  'Eres dueño de estos grupos'),
  (41,  3,  'Error borrado favor'),
  (42,  3,  'Iniciar Sesión'),
  (43,  3,  'Registrarse'),
  (44,  3,  'Bienvenido a Zenia!'),
  (45,  3,  'Crear un grupo'),
  (46,  3,  'Error general'),
  (47,  3,  'Por favor, ingrese una contraseña'),
  (48,  3,  'Por favor, introduzca un nombre de usuario'),
  (49,  3,  'Nombre de usuario no válido combinación / contraseña'),
  (50,  3,  'Página de registro'),
  (51,  3,  'Nombre de usuario'),
  (52,  3,  'Contraseña'),
  (53,  3,  'Nombre del grupo'),
  (54,  3,  'Se necesita un nombre para este grupo'),
  (55,  3,  'Crear mi nuevo grupo'),
  (56,  3,  'Detalles del grupo'),
  (57,  3,  'Ya existe ese usuario'),
  (58,  3,  'Creación de cuentas'),
  (59,  3,  'Propietario'),
  (60,  3,  'Miembros'),
  (61,  3,  'Enviar invitar'),
  (62,  3,  'Editar mi descripción del grupo'),
  (63,  3,  'Contraseña'),
  (64,  3,  'Crear mi nuevo usuario!'),
  (65,  3,  'Sesión cerrada'),
  (66,  3,  'Ha iniciado sesión con éxito'),
  (67,  3,  'Problema de seguridad'),
  (68,  3,  'Tienes que estar registrado para acceder a este'),
  (69,  3,  'Gracias por registrarse!'),
  (70,  3,  'Usted es maravilloso! muchas gracias por entrar en su nombre!'),
  (71,  3,  'Su descripción visto por otras personas de su grupo'),
  (72,  3,  'Guardar Descripción'),
  (73,  3,  'Su ubicación actual es'),
  (74,  3,  'Seleccionar país'),
  (75,  3,  'Hecho ingresar el código postal'),
  (76,  3,  'abierto'),
  (77,  3,  'cerrado'),
  (78,  3,  'tomado'),
  (79,  3,  'Rango'),
  (80,  3,  'Usuario'),
  (81,  3,  'Búsqueda avanzada'),
  (82,  3,  'No se encuentran en la base de datos para este país y el código postal ubicaciones'),
  (83,  3,  'Fecha no válida'),
  (84,  3,  'Editar descripción'),
  (85,  3,  'No se han encontrado en cadena usuarios'),
  (86,  3,  'Fecha de inicio'),
  (87,  3,  'Fecha de finalización'),
  (88,  3,  'Eliminar este usuario'),
  (89,  3,  'Confirmar contraseña'),
  (90,  3,  'Descripción de su grupo'),
  (91,  3,  'Dirección de correo electrónico conjunto'),
  (92,  3,  'Dirección de correo electrónico'),
  (93,  3,  'Página'),
  (94,  3,  'Favor Mango'),
  (95,  3,  'Confirmar'),
  (96,  3,  'Mis conversaciones'),
  (97,  3,  'Mi perfil'),
  (98,  3,  'Transacción se complete'),
  (99,  3,  'Favor se ha cerrado'),
  (100, 3,  'Usuario propietario'),
  (101, 3,  'Usuario Manipulación'),
  (102, 3,  'Favores que estoy manejando'),
  (103, 3,  'Ninguno'),
  (104, 3,  'Oferta recibido'),
  (105, 3,  'Conseguimos su oferta y te lo enseñamos ese usuario en breve. Usted puede seguir esto en su página de perfil.'),
  (106, 3,  'nuevo'),
  (107, 3,  'aceptado'),
  (108, 3,  'rechazado'),
  (109, 3,  'borrador'),
  (110, 3,  'Favorecer publicado'),
  (111, 3,  'Otros usuarios pueden ahora ver su favor y pueden ofrecer para manejarlo.'),
  (112, 3,  'Contraseña cambiada'),
  (113, 3,  'Cambiar la contraseña'),
  (114, 3,  'Ha introducido ninguna contraseña antigua o nueva contraseña. Inténtalo de nuevo.'),
  (115, 3,  'Que ya ha proporcionado una nueva contraseña, pero hay que darnos tu contraseña antigua también.'),
  (116, 3,  'Se le olvidó a darnos su nueva contraseña. Inténtalo de nuevo.'),
  (117, 3,  'Su nueva contraseña es demasiado corta. Inténtalo de nuevo.'),
  (118, 3,  'Lo que usted le dio a su antigua contraseña no es válida. Inténtalo de nuevo.'),
  (119, 3,  'Los favores que he ofrecido al servicio'),
  (120, 3,  'Ofertas para dar servicio a mis favores'),
  (121, 3,  'Si a usted le gustaría ofrecer reparar este favor, haga clic en el botón de confirmación a continuación.'),
  (122, 3,  'Mis favores abiertas'),
  (123, 3,  'Mis favores siendo atendidos'),
  (124, 3,  'Mis favores cerradas'),
  (125, 3,  'Mis proyectos Favores'),
  (126, 3,  'Cancelar un favor activa'),
  (127, 3,  'Favorecer cancelado'),
  (128, 3,  'La transacción ha sido cancelada'),
  (129, 3,  'Si desea cancelar este favor activa, haga clic en el botón de confirmación a continuación. Esto le dará la oportunidad de proporcionar un grado de la otra persona, así como darles la oportunidad de que grado.'),
  (130, 3,  'Cancelar'),
  (131, 3,  'Su transacción en un favor ha sido cancelado por la otra parte. Echa un vistazo a su página de perfil para entrar en comentarios sobre la transacción.'),
  (132, 3,  '¡Enhorabuena! Se le ha concedido el derecho de administración a Favor. Revise su perfil para más información.'),
  (133, 3,  'al usuario de grado'),
  (134, 3,  'A Favor que usted estaba manejando se ha completado.'),
  (135, 3,  'A Favor que usted era propietario de que se ha completado.'),
  (136, 3,  'Ha cancelado una transacción activa.'),
  (137, 3,  'Elegir'),
  (138, 3,  'quiere manejar'),
  (139, 3,  'Elige un controlador'),
  (140, 3,  'Confirme que desea que el siguiente usuario para manejar esta petición.'),
  (141, 3,  'Ha seleccionado un controlador para su favor!'),
  (142, 3,  'Ahora ha elegido a alguien para manejar a su favor. Ese usuario será informado, y también informará a los otros usuarios (si los hay) que no han sido seleccionados.'),
  (143, 3,  'Niñera'),
  (144, 3,  'Paseador de perros'),
  (145, 3,  'Taxi'),
  (146, 3,  'Mis mensajes del sistema'),
  (147, 3,  'Usted debe clasificar a ese usuario ahora.'),
  (148, 3,  'Usted ha recibido una oferta para manejar un favor.'),
  (149, 3,  '¿Es necesario que este favor una ubicación?'),
  (150, 3,  'Sí'),
  (151, 3,  'No'),
  (152, 3,  'Dirección Calle 1'),
  (153, 3,  'Dirección Calle 2'),
  (154, 3,  'Ciudad'),
  (155, 3,  'Estado'),
  (156, 3,  'Código Postal'),
  (157, 3,  'País'),
  (158, 3,  'Seleccione una de las ubicaciones guardadas'),
  (159, 3,  'O introducir una nueva dirección'),
  (160, 3,  'Guardar en mis favoritos'),
  (161, 3,  'Introduzca un valor de clasificación entre 0.0 y 1.0'),
  (162, 3,  'Introduzca un código postal para buscar'),
  (163, 3,  'No válida - debe ser un número entre 0 y 1'),
  (164, 3,  'Inválido - rango máximo debe ser mayor que el rango mínimo'),
  (165, 3,  'Usted'),
  (166, 3,  'aumentado'),
  (167, 3,  'disminución'),
  (168, 3,  'la reputación de'),
  (169, 3,  'su reputación'),
  (170, 3,  'por el favor'),
  (171, 3,  'Mensaje'),
  (172, 3,  'Marca de tiempo'),
  (173, 3,  'Sus favores abiertas'),
  (174, 3,  'Contraseña anterior'),
  (175, 3,  'Nueva contraseña'),
  (176, 3,  'Resolución favor'),
  (177, 3,  'Es necesario proporcionar información sobre'),
  (178, 3,  '¿Estás durmiendo? Despertarse! Tienes'),
  (179, 3,  'segundos antes de que se registran de forma automática!'),
  (180, 3,  'No se ha determinado aún'),
  (181, 3,  'no han determinado todavía'),
  (182, 3,  'No he terminado!'),
  (183, 3,  'Favorecer creado'),
  (184, 3,  'Ha creado un favor. En este momento, está en modo borrador, unviewable por otros usuarios. Puedes'),
  (185, 3,  'ahora si lo desea. Hasta que publique, permanecerá oculto. También puede publicar este favor de su página de perfil.'),
  (186, 3,  'Rango usuario'),
  (187, 3,  'Clasifique el otro usuario para la siguiente Favor'),
  (188, 3,  'feliz'),
  (189, 3,  'infeliz'),
  (190, 3,  'La clasificación se confirmó'),
  (191, 3,  'Gracias! Al proporcionar un ranking para este usuario, usted hace el sistema de un lugar más seguro para todos.'),
  (192, 3,  'sin dirección seleccionada'),
  (193, 3,  'Usted indicó que quería salvar a un lugar con este favor , pero que ha introducido nada . Si este no requiere una ubicación, haga clic'),
  (194, 3,  'Retraer'),
  (195, 3,  'Favorecer retraída'),
  (196, 3,  'Tu favor está oculto. Las ofertas han sido rechazadas . Un punto ha sido devuelto a usted.'),
  (197, 3,  'Usted debe elegir una categoría para este favor'),
  (198, 3,  'Seleccione una categoría'),
  (199, 3,  'Miscelánea'),
  (200, 3,  'Deberes'),
  (201, 3,  'No válida código de invitación'),
  (202, 3,  'Compruebe invitar código'),
  (203, 3,  'Código de invitación'),
  (204, 3,  'Enviar Código de invitación'),
  (205, 3,  'Se requiere un código de invitación para el registro'),
  (206, 3,  'Generar código de invitación'),
  (207, 3,  'Aquí hay un código de invitación . Tiene una validez de 30 minutos de este tiempo'),
  (208, 3,  'Descripción de texto demasiado grande - por favor, quédate dentro de los 200 caracteres'),
  (209, 3,  'Cambiar ubicación actual'),
  (210, 3,  'Usted no ha proporcionado ninguna información sobre una ubicación actual. Hay un botón Cancelar si no desea agregar o cambiar esta'),
  (211, 3,  'Como mínimo , debe proporcionar un código postal . Eso es lo que usamos para determinar su distancia a los favores'),
  (212, 3,  'La máxima distancia en millas'),
  (213, 3,  'error de distancia'),
  (214, 3,  '%d segundos más tarde'),
  (215, 3,  '%d minutos más tarde'),
  (216, 3,  '%d horas más tarde'),
  (217, 3,  '%d días más tarde'),
  (218, 3,  '%d años más tarde'),
  (219, 3,  'Su invitación al grupo siguiente se ha retraído'),
  (220, 3,  'Usted ha retraído su invitación para el siguiente usuario'),
  (221, 3,  'El siguiente usuario acepta su invitación a un grupo'),
  (222, 3,  'Te has unido a un nuevo grupo. Es que ahora figuran en su página de grupos'),
  (223, 3,  'Se le ha quitado de un grupo'),
  (224, 3,  'Ha eliminado un usuario de su grupo'),
  (225, 3,  '%d hace segundos'),
  (226, 3,  '%d hace minutos'),
  (227, 3,  '%d hace horas'),
  (228, 3,  '%d hace días'),
  (229, 3,  '%d años atrás'),
  (1,   4,  '搜索'),
  (2,   4,  '请求青睐'),
  (3,   4,  '注销'),
  (4,   4,  '点'),
  (5,   4,  '请输入描述'),
  (6,   4,  '发布'),
  (7,   4,  '您现在的位置'),
  (8,   4,  '你组'),
  (9,   4,  '欠％D青睐'),
  (10,  4,  '描述'),
  (11,  4,  '平均排名'),
  (12,  4,  '等级分'),
  (13,  4,  '分类'),
  (14,  4,  '请求青睐的位置'),
  (15,  4,  '位置详细信息'),
  (16,  4,  '仪表板'),
  (17,  4,  '到'),
  (18,  4,  '平均排名'),
  (19,  4,  '等级阶梯'),
  (20,  4,  '复制下面的文本，并将其发送到不管你是谁邀请到系统'),
  (21,  4,  '删除'),
  (22,  4,  '详细青睐'),
  (23,  4,  '嗨！加入我和我的朋友们一个制度，鼓励人情交易，在上'),
  (24,  4,  '状态'),
  (25,  4,  '日期'),
  (26,  4,  '您是这些群体中的一员'),
  (27,  4,  '欠人％D青睐'),
  (28,  4,  '分类'),
  (29,  4,  '是的，删除！'),
  (30,  4,  '没关系，请不要删除它'),
  (31,  4,  '利于已经被删除'),
  (32,  4,  '偏爱'),
  (33,  4,  '删除'),
  (34,  4,  '这有利于已被删除，其点已退还给你'),
  (35,  4,  '仪表盘'),
  (36,  4,  '发送信息'),
  (37,  4,  '处理'),
  (38,  4,  '消息（最多％d个字符）'),
  (39,  4,  '你确定你要删除这个忙吗？'),
  (40,  4,  '你拥有这些团体'),
  (41,  4,  '错误删除青睐'),
  (42,  4,  '登录'),
  (43,  4,  '注册'),
  (44,  4,  '欢迎您的任豆！'),
  (45,  4,  '创建一个组'),
  (46,  4,  '一般错误'),
  (47,  4,  '请输入密码'),
  (48,  4,  '请输入用户名'),
  (49,  4,  '无效的用户名/密码组合'),
  (50,  4,  '登录页面'),
  (51,  4,  '用户名'),
  (52,  4,  '密码'),
  (53,  4,  '组名'),
  (54,  4,  '一个名称是必需的这组'),
  (55,  4,  '我创建新组'),
  (56,  4,  '该组的细节'),
  (57,  4,  '该用户已经存在'),
  (58,  4,  '帐户创建'),
  (59,  4,  '业主'),
  (60,  4,  '成员'),
  (61,  4,  '发送邀请'),
  (62,  4,  '编辑我的组描述'),
  (63,  4,  '密码'),
  (64,  4,  '创建我的新用户！'),
  (65,  4,  '注销'),
  (66,  4,  '您已成功退出'),
  (67,  4,  '安全问题'),
  (68,  4,  '您需要登录才能访问该'),
  (69,  4,  '感谢您的注册！'),
  (70,  4,  '你真棒！感谢这么多的进入你的名字！'),
  (71,  4,  '你的描述所看到的别人在你的小组'),
  (72,  4,  '保存说明'),
  (73,  4,  '您的当前位置是'),
  (74,  4,  '选择国家'),
  (75,  4,  '完成输入邮政编码'),
  (76,  4,  '开放'),
  (77,  4,  '关闭'),
  (78,  4,  '拍摄'),
  (79,  4,  '秩'),
  (80,  4,  '用户'),
  (81,  4,  '高级搜索'),
  (82,  4,  '没有在数据库中找到对这个国家和邮政编码地点'),
  (83,  4,  '无效日期'),
  (84,  4,  '编辑说明'),
  (85,  4,  '没有在字符串中找到用户'),
  (86,  4,  '开始日期'),
  (87,  4,  '结束日期'),
  (88,  4,  '删除此用户'),
  (89,  4,  '确认密码'),
  (90,  4,  '你组的说明'),
  (91,  4,  '设置电子邮件地址'),
  (92,  4,  '电子邮件地址'),
  (93,  4,  '页面'),
  (94,  4,  '手柄青睐'),
  (95,  4,  '确认'),
  (96,  4,  '我的谈话'),
  (97,  4,  '我的个人资料'),
  (98,  4,  '交易完成'),
  (99,  4,  '青睐已关闭'),
  (100, 4,  '拥有用户'),
  (101, 4,  '处理用户'),
  (102, 4,  '有利于我处理'),
  (103, 4,  '无'),
  (104, 4,  '收到报价'),
  (105, 4,  '我们得到了你的报价，这在短期内会显示给该用户。您可以在您的个人资料页面跟踪此。'),
  (106, 4,  '新'),
  (107, 4,  '公认'),
  (108, 4,  '拒绝'),
  (109, 4,  '草案'),
  (110, 4,  '发表青睐'),
  (111, 4,  '其他用户现在可以查看您的青睐，并可以提供来处理它。'),
  (112, 4,  '密码修改'),
  (113, 4,  '更改密码'),
  (114, 4,  '你没有输入旧密码和新密码。再试一次。'),
  (115, 4,  '你提供了一个新的密码，但你需要向我们提供您的旧密码了。'),
  (116, 4,  '你忘了给我们您的新密码。再试一次。'),
  (117, 4,  '您的新密码太短。再试一次。'),
  (118, 4,  '你给你的旧密码是无效的。再试一次。'),
  (119, 4,  '费沃斯我提供服务'),
  (120, 4,  '提供以服务我的恩惠'),
  (121, 4,  '如果您想提供给服务这个忙，请点击下面的确认按钮。'),
  (122, 4,  '我开费沃斯'),
  (123, 4,  '我的厚待被服务'),
  (124, 4,  '我关闭费沃斯'),
  (125, 4,  '我的厚待草案'),
  (126, 4,  '取消活动飞亚'),
  (127, 4,  '赞成取消'),
  (128, 4,  '您的交易已被取消'),
  (129, 4,  '如果你想取消这个活动的青睐，点击下面的确认键。这将让您有机会提供一个档次的其他人，并且给他们一个机会给你品位。'),
  (130, 4,  '取消'),
  (131, 4,  '你在一个人情交易已取消了对方。检查你的个人资料页上输入该事务的反馈。'),
  (132, 4,  '恭喜！您已经被授予服务的忙的权利。请检查您的个人资料以获取更多信息。'),
  (133, 4,  '等级用户'),
  (134, 4,  '一个忙，你正在处理已经完成。'),
  (135, 4,  '一个忙，你都已经完成老板。'),
  (136, 4,  '您已取消的活动事务。'),
  (137, 4,  '选择'),
  (138, 4,  '想处理'),
  (139, 4,  '选择一个处理程序'),
  (140, 4,  '请确认您想以下的用户来处理这个请求。'),
  (141, 4,  '您选择的处理程序，您的青睐！'),
  (142, 4,  '现在，您已经选择了专人处理您的青睐。该用户将被告知，并且我们也将通知其他用户（如果有的话），他们没有被选中。'),
  (143, 4,  '保姆'),
  (144, 4,  '遛狗'),
  (145, 4,  '出租车'),
  (146, 4,  '我的系统消息'),
  (147, 4,  '你现在应该排名用户。'),
  (148, 4,  '你有：收到要约处理青睐。'),
  (149, 4,  '这是否需要回礼的位置？'),
  (150, 4,  '是的'),
  (151, 4,  '没有'),
  (152, 4,  '街道地址1'),
  (153, 4,  '街道地址2'),
  (154, 4,  '城市'),
  (155, 4,  '状态'),
  (156, 4,  '邮政编码'),
  (157, 4,  '国家'),
  (158, 4,  '选择您保存的位置之一'),
  (159, 4,  '或输入一个新的地址'),
  (160, 4,  '保存到我的收藏夹'),
  (161, 4,  '0.0和1.0之间输入一个值排名'),
  (162, 4,  '输入一个邮政编码搜索'),
  (163, 4,  '无效 - 必须是数字0和1之间'),
  (164, 4,  '无效的 - 最高等级必须大于最低排名'),
  (165, 4,  '你'),
  (166, 4,  '增加'),
  (167, 4,  '下降'),
  (168, 4,  '声誉'),
  (169, 4,  '你的声誉'),
  (170, 4,  '对于青睐'),
  (171, 4,  '信息'),
  (172, 4,  '时间戳'),
  (173, 4,  '他们主张开放'),
  (174, 4,  '旧密码'),
  (175, 4,  '新密码'),
  (176, 4,  '有利于解决'),
  (177, 4,  '您需要提供反馈'),
  (178, 4,  '你睡着了吗？醒来！你有'),
  (179, 4,  '秒钟，然后被自动注销！'),
  (180, 4,  '尚未确定'),
  (181, 4,  '尚未确定'),
  (182, 4,  '我没有做过！'),
  (183, 4,  '创建青睐'),
  (184, 4,  '你已经创建了一个忙。现在，它在草稿模式下，无法观看其他用户。您可以'),
  (185, 4,  '现在，如果你想。直到您发布，它将保持隐藏。您也可以从您的个人资料页面发布此青睐。'),
  (186, 4,  '用户排名'),
  (187, 4,  '排名其它用户的青睐如下'),
  (188, 4,  '高兴'),
  (189, 4,  '不快乐'),
  (190, 4,  '排名确定'),
  (191, 4,  '谢谢！通过提供该用户的排名，你让系统给大家一个更安全的地方。'),
  (192, 4,  '没有选择的地址'),
  (193, 4,  '你表示你想保存的位置与这个忙，但你输入什么。如果不需要的位置，单击'),
  (194, 4,  '撤回'),
  (195, 4,  '青睐缩回'),
  (196, 4,  '您的青睐隐时现。任何报价都被拒绝。有一点已经退还给您。'),
  (197, 4,  '你必须选择一个类别为这个忙'),
  (198, 4,  '选择一个类别'),
  (199, 4,  '杂记'),
  (200, 4,  '家庭作业'),
  (201, 4,  '无效的邀请码'),
  (202, 4,  '检查邀请码'),
  (203, 4,  '邀请码'),
  (204, 4,  '提交邀请码'),
  (205, 4,  '需要注册邀请码'),
  (206, 4,  '生成邀请码'),
  (207, 4,  '下面是一个邀请码。它是有效的，从这个时间的30分钟'),
  (208, 4,  '说明文太大 - 请留在200个字符'),
  (209, 4,  '改变当前位置'),
  (210, 4,  '您没有提供当前位置的任何信息。有一个取消按钮，如果你不希望添加或更改此'),
  (211, 4,  '最起码，你必须提供一个邮政编码。这就是我们用它来确定青睐你的距离'),
  (212, 4,  '在英里最大距离'),
  (213, 4,  '距离误差'),
  (214, 4,  '%d秒钟后'),
  (215, 4,  '在%d分钟后'),
  (216, 4,  '%d个小时后'),
  (217, 4,  '%d天后'),
  (218, 4,  '%d年以后'),
  (219, 4,  '您的邀请到以下组已收回'),
  (220, 4,  '你已经收回您的邀请到以下用户'),
  (221, 4,  '以下用户接受你的邀请组'),
  (222, 4,  '你已经加入了一个新的群体。它现在在你的网页组上市'),
  (223, 4,  '你从一组被删除'),
  (224, 4,  '您从组中删除用户'),
  (225, 4,  '%d 秒前'),
  (226, 4,  '%d 分钟前'),
  (227, 4,  '%d 小时前'),
  (228, 4,  '%d 天前'),
  (229, 4,  '%d 几年前'),
  (1,   5,  'חיפוש'),
  (2,   5,  'בעד בקשה'),
  (3,   5,  'התנתקות'),
  (4,   5,  'נקודות'),
  (5,   5,  'נא להזין תיאור'),
  (6,   5,  'לפרסם'),
  (7,   5,  'מיקום נוכחי'),
  (8,   5,  'הקבוצות שלך'),
  (9,   5,  'הוא חייב טובות %d'),
  (10,  5,  'תיאור'),
  (11,  5,  'ממוצע דירוג'),
  (12,  5,  'ציון דרגה'),
  (13,  5,  'קטגוריות'),
  (14,  5,  'בעד בקשה עם מיקום'),
  (15,  5,  'פרטי מיקום'),
  (16,  5,  'לוח המחוונים'),
  (17,  5,  'ל'),
  (18,  5,  'ממוצע דירוג'),
  (19,  5,  'סולם דירוג'),
  (20,  5,  'העתק את הטקסט הבא ולשלוח אותו לכל מי שאתה מזמין למערכת'),
  (21,  5,  'מחק'),
  (22,  5,  'להעדיף פרטים'),
  (23,  5,  'היי ! הצטרף אלייוהחברים שלי במערכת שמעודדת את המסחר של טובות הנאה , ב'),
  (24,  5,  'סטטוס'),
  (25,  5,  'תאריך'),
  (26,  5,  'אתה חבר של קבוצות אלה'),
  (27,  5,  'חייב טובות %d אנשים'),
  (28,  5,  'קטגוריות'),
  (29,  5,  'כן, למחוק!'),
  (30,  5,  'Nevermind, אל תמחק אותו'),
  (31,  5,  'טובה נמחקה'),
  (32,  5,  'להעדיף'),
  (33,  5,  'נמחק'),
  (34,  5,  'בעד זה נמחק, הנקודות שלה כבר תוחזר אליך'),
  (35,  5,  'לוח מחוונים'),
  (36,  5,  'שלח הודעה'),
  (37,  5,  'ידית'),
  (38,  5,  'הודעה (עד תווי %d)'),
  (39,  5,  'האם אתה בטוח שאתה רוצה למחוק את הטובה הזאת?'),
  (40,  5,  'אתה הבעלים של קבוצות אלה'),
  (41,  5,  'בעד מחיקת שגיאה'),
  (42,  5,  'כניסה'),
  (43,  5,  'הרשמה'),
  (44,  5,  'ברוכים הבאים לדניה!'),
  (45,  5,  'צור קבוצה'),
  (46,  5,  'שגיאה כללית'),
  (47,  5,  'יש להזין סיסמא'),
  (48,  5,  'יש להזין שם משתמש'),
  (49,  5,  'שם משתמש לא חוקי / שילוב סיסמא'),
  (50,  5,  'דף כניסה'),
  (51,  5,  'שם משתמש'),
  (52,  5,  'סיסמא'),
  (53,  5,  'שם קבוצה'),
  (54,  5,  'שם נדרשלקבוצה זו'),
  (55,  5,  'יצירת הקבוצה החדשה שלי'),
  (56,  5,  'פרטים שלהקבוצה'),
  (57,  5,  'משתמש שכבר קיים'),
  (58,  5,  'יצירת חשבון'),
  (59,  5,  'בעלים'),
  (60,  5,  'חברים'),
  (61,  5,  'שלח הזמנה'),
  (62,  5,  'ערוך תיאור הקבוצה שלי'),
  (63,  5,  'סיסמא'),
  (64,  5,  'צור המשתמש החדש שלי!'),
  (65,  5,  'מתנתק'),
  (66,  5,  'יש לך מחובר בהצלחה'),
  (67,  5,  'בעיה בטחונית'),
  (68,  5,  'אתה צריך להיות מחובר כדי לגשת זה'),
  (69,  5,  'תודה על הרשמה!'),
  (70,  5,  'אתה מדהים! תודה רבה להזנת השם שלך!'),
  (71,  5,  'התיאור שלך נראה כמו על ידי אחרים בקבוצה שלך'),
  (72,  5,  'תיאור שמור'),
  (73,  5,  'המיקום הנוכחי שלך הוא'),
  (74,  5,  'בחר מדינה'),
  (75,  5,  'תסיים להזין את מיקוד'),
  (76,  5,  'פתוח'),
  (77,  5,  'סגור'),
  (78,  5,  'לקחתי'),
  (79,  5,  'דירוג'),
  (80,  5,  'משתמש'),
  (81,  5,  'חיפוש מתקדם'),
  (82,  5,  'לא נמצאו מיקומיםבמסד נתונים למדינה הזוומיקוד'),
  (83,  5,  'תאריך לא חוקי'),
  (84,  5,  'ערוך תיאור'),
  (85,  5,  'לא נמצאו משתמשים במחרוזת'),
  (86,  5,  'תאריך ההתחלה'),
  (87,  5,  'תאריך סיום'),
  (88,  5,  'הסר משתמש זה'),
  (89,  5,  'אשר סיסמא'),
  (90,  5,  'התיאור של הקבוצה שלך'),
  (91,  5,  'כתובת הדוא"ל של קבוצה'),
  (92,  5,  'כתובת דוא"ל'),
  (93,  5,  'דף'),
  (94,  5,  'לטובת ידית'),
  (95,  5,  'אשר'),
  (96,  5,  'השיחות שלי'),
  (97,  5,  'הפרופיל שלי'),
  (98,  5,  'העסקה הושלמה'),
  (99,  5,  'טובה נסגרה'),
  (100, 5,  'משתמשים בעלות'),
  (101, 5,  'משתמשים טיפול'),
  (102, 5,  'אני מעדיף טיפול ב'),
  (103, 5,  'אף אחד'),
  (104, 5,  'הצעה שקיבלה'),
  (105, 5,  'יש לנו ההצעה שלך ויציגו אותו למשתמש, כי זמן קצר. אתה יכול לעקוב אחר זה בעמוד הפרופיל שלך.'),
  (106, 5,  'חדש'),
  (107, 5,  'מקובל'),
  (108, 5,  'נדחה'),
  (109, 5,  'טיוטה'),
  (110, 5,  'מעדיף שפורסם'),
  (111, 5,  'משתמשים אחרים יכולים כעת להציג לטובתך ועשויות להציע כדי להתמודד עם זה.'),
  (112, 5,  'סיסמא השתנתה'),
  (113, 5,  'שינוי סיסמא'),
  (114, 5,  'אתה נכנס ללא סיסמא ישנה או סיסמא חדשה. נסה שוב.'),
  (115, 5,  'שסיפקת סיסמא חדשה, אבל אתה צריך לתת לנו את הסיסמה שלך ישנה מדי.'),
  (116, 5,  'שכחת לתת לנו את הסיסמה החדשה שלך. נסה שוב.'),
  (117, 5,  'הסיסמה החדשה שלך היא קצרה מדי. נסה שוב.'),
  (118, 5,  'מה שנתת לסיסמא הישנה שלך אינו חוקי. נסה שוב.'),
  (119, 5,  'טובות הנאה שהוצעתי לשירות'),
  (120, 5,  'מציע שירות טובה שלי'),
  (121, 5,  'אם אתה רוצה להציע שירות זה לטובת, לחץ על לחצן אישור להמשך.'),
  (122, 5,  'המצדדים הפתוחים שלי'),
  (123, 5,  'מצדדיי זמן הטיפול'),
  (124, 5,  'המצדדים סגורים שלי'),
  (125, 5,  'מצדדי הטיוטה שלי'),
  (126, 5,  'לבטל בעד פעיל'),
  (127, 5,  'להעדיף בוטל'),
  (128, 5,  'העסקה שלך בוטלה'),
  (129, 5,  'אם ברצונכם לבטל בעד פעיל זה, לחץ על כפתור האישור בהמשך. זה ייתן לך את ההזדמנות לספק כיתה לאדם האחר, כמו גם לתת להם הזדמנות לכיתתך.'),
  (130, 5,  'לבטל'),
  (131, 5,  'העסקה שלך על טובה בוטלה על ידי הצד השני. בדקו את דף הפרופיל שלך להיכנס למשוב על עסקה ש.'),
  (132, 5,  'מזל טוב! הוענק לך את הזכות לשירות טובה. בדוק את הפרופיל שלך לקבלת מידע נוספת.'),
  (133, 5,  'למשתמשי כיתה'),
  (134, 5,  'טובה שהיית בטיפול הושלם.'),
  (135, 5,  'טובה שהיית הבעלים של הושלם.'),
  (136, 5,  'שבטלת את עסקה פעילה.'),
  (137, 5,  'בחר'),
  (138, 5,  'רוצה להתמודד'),
  (139, 5,  'בחר מטפל'),
  (140, 5,  'ודא שאתה רוצה המשתמש הבא לטפל בבקשה זו.'),
  (141, 5,  'בחרת מטפל לטובתך!'),
  (142, 5,  'עכשיו שבחרת מישהו שיטפל בטובתך. המשתמש שיקבל הודעה, ואנחנו גם נודיע למשתמשים האחרים (אם בכלל) שהם לא נבחרו.'),
  (143, 5,  'שמרטפות'),
  (144, 5,  'כלב לטיול'),
  (145, 5,  'מונית'),
  (146, 5,  'הודעות המערכת שלי'),
  (147, 5,  'אתה צריך לדרג את המשתמש שעכשיו.'),
  (148, 5,  'יש לך קיבל הצעה לטיפול טובה.'),
  (149, 5,  'האם זה לטובה צריכה מיקום?'),
  (150, 5,  'כן'),
  (151, 5,  'לא'),
  (152, 5,  'כתובת רחוב 1'),
  (153, 5,  'כתובת רחוב 2'),
  (154, 5,  'עיר'),
  (155, 5,  'מדינה'),
  (156, 5,  'מיקוד'),
  (157, 5,  'מדינה'),
  (158, 5,  'בחר באחד מהמיקומים השמורים'),
  (159, 5,  'או להיכנס לכתובת חדשה'),
  (160, 5,  'שמור למועדפים שלי'),
  (161, 5,  'הזן ערך דירוג בין 0.0 ו 1.0'),
  (162, 5,  'הזן מיקוד לחיפוש'),
  (163, 5,  'לא תקף - חייב להיות מספר בין 0 ל -1'),
  (164, 5,  'לא תקף - דרגה המרבית חייבת להיות גדולה מ דרגה מינימאלית'),
  (165, 5,  'אתם'),
  (166, 5,  'גדל'),
  (167, 5,  'ירידה'),
  (168, 5,  'המוניטין של'),
  (169, 5,  'המוניטין שלך'),
  (170, 5,  'לטובה'),
  (171, 5,  'הודעה'),
  (172, 5,  'חותם זמן'),
  (173, 5,  'טובות הפתוחות'),
  (174, 5,  'סיסמא הישנה'),
  (175, 5,  'סיסמא חדשה'),
  (176, 5,  'החלטה לטובת'),
  (177, 5,  'אתה צריך לספק משוב על'),
  (178, 5,  'האם אתה ישן? תתעורר! יש לך'),
  (179, 5,  'שניות לפני שאתה מחובר באופן אוטומטי!'),
  (180, 5,  'עדיין לא נקבע'),
  (181, 5,  'עדיין לא נקבע'),
  (182, 5,  'אני לא עשיתי!'),
  (183, 5,  'מעדיף שנוצר'),
  (184, 5,  'שיצרת לטובת. נכון לעכשיו, הוא נמצא במצב טיוטה, unviewable על ידי משתמשים אחרים. אתה יכול'),
  (185, 5,  'זה עכשיו, אם ירצה. עד שתפרסם, הוא יישאר נסתר. אתה יכול גם לפרסם את הטובה הזאת מדף הפרופיל שלך.'),
  (186, 5,  'משתמשים דרגה'),
  (187, 5,  'דרג את המשתמש האחר לטובה הבאה'),
  (188, 5,  'מאושר'),
  (189, 5,  'אומלל'),
  (190, 5,  'דירוג אישר'),
  (191, 5,  'תודה! על ידי מתן דירוג עבור משתמש זה, אתה להפוך את המערכת למקום בטוח יותר עבור כולם.'),
  (192, 5,  'אין כתובת שנבחרה'),
  (193, 5,  'שציינת שאתה רוצה לשמור אתמיקום עם הטובה הזאת , אבל אתה נכנס שום דבר . אם זה אינו מחייבמיקום , לחץ על'),
  (194, 5,  'לחזור בו'),
  (195, 5,  'להעדיף חזר בי'),
  (196, 5,  'לטובתך עכשיו חבויה . כל הצעות נדחו . נקודה הוחזרה לך .'),
  (197, 5,  'עליך לבחורקטגוריה עבור הטובה הזאת'),
  (198, 5,  'בחר קטגוריה'),
  (199, 5,  'קוֹבֶץ מְעוּרָב'),
  (200, 5,  'שיעורי בית'),
  (201, 5,  'להזמין קוד לא חוקי'),
  (202, 5,  'בדוק מזמין את הקוד'),
  (203, 5,  'קוד הזמנה'),
  (204, 5,  'שלח קוד הזמנה'),
  (205, 5,  'קוד הזמנה נדרש לרישום'),
  (206, 5,  'ליצור קוד הזמנה'),
  (207, 5,  'הנהקוד הזמנה . זה תקף למשך 30 דקות מהזמן הזה'),
  (208, 5,  'טקסט תיאור גדול מדי - בבקשה להישאר בתוך 200 תווים'),
  (209, 5,  'לשנות את המיקום נוכחי'),
  (210, 5,  'אתה לא סיפקת כל מידע עלמיקום נוכחי . ישלחצן ביטול אם אתה לא רוצה להוסיף או לשנות את זה'),
  (211, 5,  'לכל הפחות , עליך לספקמיקוד . כי '' מה שאנו משתמשים כדי לקבוע את המרחק שלךלטובות הנאה'),
  (212, 5,  'מרחק מקסימאלי במייל'),
  (213, 5,  'שגיאת מרחק'),
  (214, 5,  '%d שניות מאוחר יותר'),
  (215, 5,  '%d דקות מאוחר יותר'),
  (216, 5,  '%d שעות מאוחר יותר'),
  (217, 5,  '%d ימים לאחר מכן'),
  (218, 5,  '%d שנים מאוחר יותר'),
  (219, 5,  'ההזמנה שלך לקבוצה הבאה כבר חזר בו'),
  (220, 5,  'יש לך את ההזמנה שלך חזרלמשתמש הבא'),
  (221, 5,  'המשתמש הבא קיבל את ההזמנה לקבוצה שלך'),
  (222, 5,  'יש לך הצטרף לקבוצה חדשה . הוא רשום כעתבדף הקבוצות שלך'),
  (223, 5,  'אתה הוסרמקבוצה'),
  (224, 5,  'שהסרת אתמשתמש מהקבוצה שלך'),
  (225, 5,  '%d לפני שניות'),
  (226, 5,  '%d לפני דקות'),
  (227, 5,  '%d לפני שעות'),
  (228, 5,  '%d לפני ימים'),
  (229, 5,  '%d לפני שנים');


